import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavigationSidebar from "@/components/layout/navigation-sidebar";
import Searchbar from "@/components/ui/searchbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex relative">
          <div>
            <NavigationSidebar />
          </div>
          <div className="flex-1">
            <div className="py-4 px-8 sticky z-30 top-0 bg-white">
              <Searchbar className="" />
            </div>
            <div className="px-8  py-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
